AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Description: Type of this BacketName.
    Type: String
  AllowIP:
    Description: Type of this IP Address.
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: IPAllow
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - /*
            Condition:
              IpAddress:
                aws:SourceIp:
                  - !Ref AllowIP
          - Sid: IPDeny
            Effect: Deny
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - /*
            Condition:
              NotIpAddress:
                aws:SourceIp:
                  - !Ref AllowIP
      Bucket: !Ref S3Bucket
Outputs:
  S3BucketName:
    Value: !Ref S3BucketName
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !Ref S3Bucket
    Description: Name of S3 bucket to hold website content
